import os
from django.test import TestCase, override_settings

from design.models import Organism, Gene, Transcript


DDX11L1_sequence = ''.join("""GTTAACTTGCCGTCAGCCTTTTCTTTGACCTCTTCTTTCTGTTCATGTGTATTTGCTGTC
TCTTAGCCCAGACTTCCCGTGTCCTTTCCACCGGGCCTTTGAGAGGTCACAGGGTCTTGA
TGCTGTGGTCTTCATCTGCAGGTGTCTGACTTCCAGCAACTGCTGGCCTGTGCCAGGGTG
CAAGCTGAGCACTGGAGTGGAGTTTTCCTGTGGAGAGGAGCCATGCCTAGAGTGGGATGG
GCCATTGTTCATCTTCTGGCCCCTGTTGTCTGCATGTAACTTAATACCACAACCAGGCAT
AGGGGAAAGATTGGAGGAAAGATGAGTGAGAGCATCAACTTCTCTCACAACCTAGGCCAG
TAAGTAGTGCTTGTGCTCATCTCCTTGGCTGTGATACGTGGCCGGCCCTCGCTCCAGCAG
CTGGACCCCTACCTGCCGTCTGCTGCCATCGGAGCCCAAAGCCGGGCTGTGACTGCTCAG
ACCAGCCGGCTGGAGGGAGGGGCTCAGCAGGTCTGGCTTTGGCCCTGGGAGAGCAGGTGG
AAGATCAGGCAGGCCATCGCTGCCACAGAACCCAGTGGATTGGCCTAGGTGGGATCTCTG
AGCTCAACAAGCCCTCTCTGGGTGGTAGGTGCAGAGACGGGAGGGGCAGAGCCGCAGGCA
CAGCCAAGAGGGCTGAAGAAATGGTAGAACGGAGCAGCTGGTGATGTGTGGGCCCACCGG
CCCCAGGCTCCTGTCTCCCCCCAGGTGTGTGGTGATGCCAGGCATGCCCTTCCCCAGCAT
CAGGTCTCCAGAGCTGCAGAAGACGACGGCCGACTTGGATCACACTCTTGTGAGTGTCCC
CAGTGTTGCAGAGGTGAGAGGAGAGTAGACAGTGAGTGGGAGTGGCGTCGCCCCTAGGGC
TCTACGGGGCCGGCGTCTCCTGTCTCCTGGAGAGGCTTCGATGCCCCTCCACACCCTCTT
GATCTTCCCTGTGATGTCATCTGGAGCCCTGCTGCTTGCGGTGGCCTATAAAGCCTCCTA
GTCTGGCTCCAAGGCCTGGCAGAGTCTTTCCCAGGGAAAGCTACAAGCAGCAAACAGTCT
GCATGGGTCATCCCCTTCACTCCCAGCTCAGAGCCCAGGCCAGGGGCCCCCAAGAAAGGC
TCTGGTGGAGAACCTGTGCATGAAGGCTGTCAACCAGTCCATAGGCAAGCCTGGCTGCCT
CCAGCTGGGTCGACAGACAGGGGCTGGAGAAGGGGAGAAGAGGAAAGTGAGGTTGCCTGC
CCTGTCTCCTACCTGAGGCTGAGGAAGGAGAAGGGGATGCACTGTTGGGGAGGCAGCTGT
AACTCAAAGCCTTAGCCTCTGTTCCCACGAAGGCAGGGCCATCAGGCACCAAAGGGATTC
TGCCAGCATAGTGCTCCTGGACCAGTGATACACCCGGCACCCTGTCCTGGACACGCTGTT
GGCCTGGATCTGAGCCCTGGTGGAGGTCAAAGCCACCTTTGGTTCTGCCATTGCTGCTGT
GTGGAAGTTCACTCCTGCCTTTTCCTTTCCCTAGAGCCTCCACCACCCCGAGATCACATT
TCTCACTGCCTTTTGTCTGCCCAGTTTCACCAGAAGTAGGCCTCTTCCTGACAGGCAGCT
GCACCACTGCCTGGCGCTGTGCCCTTCCTTTGCTCTGCCCGCTGGAGACGGTGTTTGTCA
TGGGCCTGGTCTGCAGGGATCCTGCTACAAAGGTGAAACCCAGGAGAGTGTGGAGTCCAG
AGTGTTGCCAGGACCCAGGCACAGGCATTAGTGCCCGTTGGAGAAAACAGGGGAATCCCG
AAGAAATGGTGGGTCCTGGCCATCCGTGAGATCTTCCCAGGGCAGCTCCCCTCTGTGGAA
TCCAATCTGTCTTCCATCCTGCGTGGCCGAGGGCCAGGCTTCTCACTGGGCCTCTGCAGG
AGGCTGCCATTTGTCCTGCCCACCTTCTTAGAAGCGAGACGGAGCAGACCCATCTGCTAC
TGCCCTTTCTATAATAACTAAAGTTAGCTGCCCTGGACTATTCACCCCCTAGTCTCAATT
TAAGAAGATCCCCATGGCCACAGGGCCCCTGCCTGGGGGCTTGTCACCTCCCCCACCTTC
TTCCTGAGTCATTCCTGCAGCCTTGCTCCCTAACCTGCCCCACAGCCTTGCCTGGATTTC
TATCTCCCTGGCTTGGTGCCAGTTCCTCCAAGTCGATGGCACCTCCCTCCCTCTCAACCA
CTTGAGCAAACTCCAAGACATCTTCTACCCCAACACCAGCAATTGTGCCAAGGGCCATTA
GGCTCTCAGCATGACTATTTTTAGAGACCCCGTGTCTGTCACTGAAACCTTTTTTGTGGG
AGACTATTCCTCCCATCTGCAACAGCTGCCCCTGCTGACTGCCCTTCTCTCCTCCCTCTC
ATCCCAGAGAAACAGGTCAGCTGGGAGCTTCTGCCCCCACTGCCTAGGGACCAACAGGGG
CAGGAGGCAGTCACTGACCCCGAGACGTTTGCATCCTGCACAGCTAGAGATCCTTTATTA
AAAGCACACTGTTGGTTTCTG""".splitlines())

KLHL17_205_sequence = ''.join("""CGCGTCCGTTAAGCCCGCGGGTCCTCCGCGAATCGGCGGTGGGTCCGGCAGCCGAATGCA
GCCCCGCAGCGAGCGCCCGGCCGGCAGGACGCAGAGCCCGGAGCACGGCAGCCCGGGGCC
CGGGCCCGAGGCGCCGCCGCCTCCACCGCCGCAGCCGCCGGCGTGAGTGGGCGGGGGTCG
GGGCGCGGGGGGCGGCCTCGGGACCTGCGCGGCCCCCGCCCTCGCGTCCGCTCGCAGAAG
GGGCGGGGGCCGCTTCCGAGGGCCGGGGGAGGTCGGGACTCAGGTGCGGAGCGGGGTCGG
CCCGGAGTAGGTTCCCCACCCGCGCCCCGCGCGCCCAGGACGCGACTCCCGCTGCGGTCC
CGAGAGGGCGGCTAGGGACGCGGAGGAGCTGAGCTCGTGGGGGCGCCGGGAAGCGGGGCC
GGACGCGGGGCTCTGTTCGCGGCTCTGACTACGCCCCAGGGGAGCAGGGGCGCAGCGGAG
GCCTGGACACGGCGCGCTCCGGGGCGGGGGTCCTTGGCGGAGGTCAGGCGAGGGCTGCCG
GCGCCCCCGTCGCACCAGGGGCTGGGTCCCCGCGGGCTGCCCGGGCCCCCCAGCGGCTCC
AGGGCGGGCGGGCGGCTCCAGCGGGGCGAAGCCTGACCCGCCCGCCTCCTGCAGCCCCGA
GGCAGAGCGCACGCGGCCCCGGCAGGCTCGGCCCGCAGCCCCCATGGAGGGAGCCGTGCA
GCTGCTGAGCCGCGAGGGCCACAGCGTGGCCCACAACTCCAAGCGGCACTACCACGATGC
CTTCGTGGCCATGAGCCGCATGCGCCAGCGCGGCCTCCTGTGCGACATCGTCCTGCACGT
GGCTGCCAAGGAGATCCGTGCGCACAAAGTGGTGCTGGCCTCCTGCAGCCCCTACTTCCA
CGCCATGTTCACAAGCAAGTACCCGCCTGGGCGGCGCTGGGGGCTCCGTGGGTCCCTCGG
GTCAGCTCGTGTAACCCGCTGTCCCCGCAGATGAGATGAGCGAGAGCCGCCAGACCCACG
TGACGCTGCACGACATCGACCCTCAGGCCTTGGACCAGCTGGTGCAGTTTGCCTACACGG
CTGAGATTGTGGTGGGCGAGGGCAATGTGCAGGTGAGGGCTCCCTCACCCGGATCCCGGT
GTCCCCCGACCCTGTGCCTCCCTCACCTGCCTCTCGGTGCCCCGTAGACTCTGCTCCCAG
CCGCCAGTCTCCTGCAGCTGAATGGCGTCCGAGACGCTTGCTGCAAGTTTCTACTGAGTC
AGCTCGACCCCTCCAACTGCCTGGGTATCCGGGGCTTTGCCGATGCGCACTCCTGCAGCG
ACCTGCTCAAGGCCGCCCACAGGTACGTGCTGCAGCACTTCGTGGACGTGGCCAAGACCG
AGGAGTTTATGCTGCTGCCCCTGAAACAGGTAACAGCTGGCGGGCCCAGCCCTCGCCCCC
CACCCCACCCCACCCCAGTCTTTGTCTTTGACTCCCGACCCCGTTTTGTTCCTGACACAG
CCCTGCCCACAATCCTTAGTGCCTGCTGTGTGTCCCCGAGACCTTTCTGGATCTGGGCCC
CCCAGGAGCCTCGTCTGTGGCTCCTGACTCTGCTCGGCCCCTCCCAGTATGAACACTCAG
CCCCCACCTGCTAACCCTCCCTCCTAGGCATCTTCAGGGCTCCCTGGGTCCACAGGACCC
TCCCCAGATCTCAGGTCTGAGGACCCCCACTCCCAGGTTCTGGAACTGGTCTCTAGCGAC
AGCCTGAACGTGCCTTCAGAGGAGGAGGTCTACCGAGCCGTCCTGAGCTGGGTGAAACAC
GACGTGGACGCCCGCAGGCAGCATGTCCCACGGGTGAGGCGCGGCCGCGGGGGGCTCCCA
CAGCATCCAGGAGGGCATGCAGGTGGCTGAGGGCCTGGTGCACCCTGACCTTCCCCGAGT
TCAGGGACTCCGTGGGGGTGGTGCCCCCACCTGTCTGAAGAAGAATCCATCACACAGGTG
GTACGGGCATCTGGGGGGTTGTCTCAGCCCTGACGCCCAGTGTGCCCGAGGGTCCCGCCT
GACCTTGGCGTTCCCTGCACCCCAGCTCATGAAGTGTGTGCGGCTGCCCTTGCTGAGCCG
CGACTTCCTGCTGGGCCACGTGGATGCCGAGAGCCTGGTGAGGCACCACCCTGACTGCAA
GGACCTCCTCATCGAGGCCCTGAAGTTCCACCTGCTGCCTGAGCAGAGGGGCGTCCTAGG
CACCAGCCGCACACGTCCCCGGCGCTGCGAGGGGGCCGGGCCTGTGCTTTTTGCTGTGGG
TATGGCCCCCCGCCCGTTTCCCTCTTGCCCTGTGCCTTCTACTCCCCACCAGCACAAGCC
CACCCCACCTGTGCCGGTCAGGTCCTGACCTGCCCCTCCGCCCCTCCATTCAGGGGCCTC
TCCAGGAGCCTGGGGTGTGGCCCAGCAGTGGGATCCACTCACGAGTCCCGTCTCCACCTG
CCCTCCCCAGGCGGCGGGAGCCTGTTTGCCATCCACGGAGACTGTGAGGCCTACGACACG
CGCACCGACCGCTGGCACGTGGTGGCCTCCATGTCCACGCGCCGGGCCCGGGTGGGAGTG
GCTGCGGTGGGGAACCGGCTCTATGCTGTGGGCGGGTAAGCCTGGAGGCTGGACTTGGGT
CGGGTCTGGCACGTGCCCGCCAGGCCAGTCTTGACCTGCAGTGGCTTAATTCCGCTAGCT
ATGATGGGACCTCAGACCTGGCTACCGTGGAGTCCTACGACCCCGTGACTAACACGTGGC
AGCCGGAGGTGTCCATGGGCACAAGGCGAAGCTGCCTGGGTGTGGCCGCCTTGCATGGAC
TCCTGTACTCGGCCGGCGGCTATGACGGGGCCTCCTGCCTGAACAGGTAGTTGGGGTTGG
GGCCCCAGTGGCTTTGTACAGTCCATCTGCAAGAGGCAAGTTTGTGTCACCATCACAGGG
GTCGTATCTGATGGGGTGTTAAAGGAGGTGATCCGCGAGGCCGTTTCACCCCAGGCCACT
GCCACACTGGGCCTGAACTCTTGGCTTTGCTGCCCCAGTGCCCTTTCCTCTCTCGGGTCC
TTACCCCCAGTCCAGAGGCTGGGCCCAGGTGGGTGTGCACCCAGGGTTGTTCAGGCAGCC
AGGGTCCTGTGCCCACCAGCGGGCCCTGCCTGGTAGGACTTTGCGGTCTGAGTTTGACTC
CTAGGGTAAGATTTCAGCCATTCCGCTGGGGAGGGCAGGTCCTGGGGCCGGGACGCCTTT
CTGTCTCTGCTGAGCTGTGGCTGCGGTCCTGGTGCCCACAGTGCTGAACGCTACGACCCC
CTGACCGGAACGTGGACGTCCGTCGCTGCCATGAGCACCCGGAGGCGCTATGTGCGAGTG
GCCACGCTTGGTGGGTGATGGGGCCTGCCTGGGGGGCATCCCCACCTTCCCCCACCGTGG
AGACCCCACTCCCAGCAGGAGTGCCACGGGTGTGTTGACTTCCGGCAGATGGGAACCTGT
ATGCTGTGGGCGGCTACGACAGCTCCTCACACCTGGCCACTGTGGAGAAGTATGAGCCCC
AGGTGCATAGTGCACCCCTCCTGGCCACCCCCTCCCGTGCGCCGCGGGGCCCTCCTCCCT
CTGTTTACCCACATCCCCCCCATTCCTGACACCCCACCCTGGAGTCGGGGCTGCGGCAGA
GGAGGGATGCCAGTGGCGGGTCTGCGTCCAGCCCACGCCCTCGCCCCCAGGTGAACGTGT
GGTCGCCCGTGGCGTCCATGCTGAGCCGACGCAGCTCAGCGGGCGTGGCCGTGCTGGAGG
GTGCCCTGTACGTGGCAGGGGGCAACGACGGCACCAGCTGCCTCAACTCGGTAGAGAGAT
ACAGTCCAAAGGCTGGAGCCTGGGAAAGCGTGGCGCCCATGAATATCCGCAGGTCCGCAG
TGGGGCTGCGGGGAGGGGGGCGCGGGTCCGCAGTGGGGCTGTGGGAGGGGTCCGCGCGTC
CGCAGTGGGGATGTGCTGCGGGGAGGGGGGCGCGGGTCCGCAGTGGGGATGTGCTGCCGG
GAGGGGGGCGCGGGTCCGCAGTGGGGATGTGCTGCCGGGAGGGGGGCGCGGGTCCGCAGT
GGGGATGTGCTGCCGGGAGGGGGGCGCGGGTCCGCAGTGGGGATGTGCTGCCGGGAGGGG
GGCGCGGGTCCGCAGTGGGGATGTGCTGCCGGGAGGGGGGCGCGGGTCCGCAGTGGGGAT
GTGCTGTGAGAAGGGAGTTCTCCCAACCTCAGCGAGCATGTCCCGCCACCACCCCTTTTT
GTGGTGCAGCCCCTCCCCCCGCATCCCTTCCTGCAGCCAGGGGCTCACCCCGCCTTCCCC
CCAGGAGCACGCATGACCTGGTGGCCATGGACGGATGGTTGTACGCCGTGGGGGGTAACG
ACGGTAGCTCCAGCCTCAACTCCATCGAGAAGTACAACCCGAGGACCAACAAGTGGGTGG
CCGCATCCTGCATGTTCACCCGGCGCAGCAGTGTGGGTGTGGCGGTGCTGGAGCTGCTCA
ATTTCCCGCCGCCATCCTCCCCGACGCTGTCCGTGTCCTCCACCAGCCTCTGACCCACCT
ACCACCAGAGGCCTGCAGCCTCCCACATGCCTTAAGGGGACCGTGGCCCCCACCAGGGAC
GTCCTGCGCCATCCGTTCACGTCTCTGCATCCATTCCTTCATGTCTTTATTTAGTTGTTT
ATTTATTTAGTTATTTATCTTATTTATTGAGGGGTGAGGAGTGCCACGGCTGCCCGTTTA
CACCTTTAGCGTCTGGTCCTCCTGCGTGTCCTCCCCTCCACTGCCTGCATGGGGGGCGCG
GGGAGTGACCAGGCGGGGGCCTCACCGCCCCAGGGCCGTTGCCTGCTCAGACCTTGCAGG
CTGTGGAGCAAGAGGCCCTGGGTCTCTCCAAGCAGCTGCAGACCCCAGCTCGAATTTTGC
ACATGGCGGGGTCCCGGGAAGGGTGGGGAGCAGTTGTCCTTCCT""".splitlines())

KLHL17_205_cds = ''.join("""ATGAAGTGTGTGCGGCTGCCCTTGCTGAGCCGCGACTTCCTGCTGGGCCACGTGGATGCC
GAGAGCCTGGTGAGGCACCACCCTGACTGCAAGGACCTCCTCATCGAGGCCCTGAAGTTC
CACCTGCTGCCTGAGCAGAGGGGCGTCCTAGGCACCAGCCGCACACGTCCCCGGCGCTGC
GAGGGGGCCGGGCCTGTGCTTTTTGCTGTGGGCGGCGGGAGCCTGTTTGCCATCCACGGA
GACTGTGAGGCCTACGACACGCGCACCGACCGCTGGCACGTGGTGGCCTCCATGTCCACG
CGCCGGGCCCGGGTGGGAGTGGCTGCGGTGGGGAACCGGCTCTATGCTGTGGGCGGCTAT
GATGGGACCTCAGACCTGGCTACCGTGGAGTCCTACGACCCCGTGACTAACACGTGGCAG
CCGGAGGTGTCCATGGGCACAAGGCGAAGCTGCCTGGGTGTGGCCGCCTTGCATGGACTC
CTGTACTCGGCCGGCGGCTATGACGGGGCCTCCTGCCTGAACAGTGCTGAACGCTACGAC
CCCCTGACCGGAACGTGGACGTCCGTCGCTGCCATGAGCACCCGGAGGCGCTATGTGCGA
GTGGCCACGCTTGATGGGAACCTGTATGCTGTGGGCGGCTACGACAGCTCCTCACACCTG
GCCACTGTGGAGAAGTGA""".splitlines())


class OrganismTestCase(TestCase):

    @override_settings(DESIGN_ASSEMBLIES_FOLDER='tests/testdata')
    def test_add_to_database_gencode(self):
        Organism.add_to_database('gencode test', 'chr1',
                                 os.path.join(os.path.dirname(os.path.abspath(__file__)), 'testdata', 'gencode.gff'),
                                 'source', 'gencode', 'sequencesearch', 'gencode test', silent=False)
        organism = Organism.objects.first()
        self.assertEqual(organism.name, 'gencode test')
        self.assertEqual(Gene.objects.count(), 10)
        self.assertEqual(Transcript.objects.count(), 19)


@override_settings(DESIGN_ASSEMBLIES_FOLDER=os.path.join(os.path.dirname(os.path.abspath(__file__)), 'testdata'))
class GeneTestCase(TestCase):

    def setUp(self) -> None:
        Organism.add_to_database('gencode test', 'chr1',
                                 os.path.join(os.path.dirname(os.path.abspath(__file__)), 'testdata', 'gencode.gff'),
                                 'source', 'gencode', 'sequencesearch', 'gencode test', silent=True)
        self.gene = Gene.objects.first()

    def test_extract_sequence(self):
        self.assertEqual(self.gene.name, 'DDX11L1')
        self.assertEqual(self.gene.sequence, DDX11L1_sequence)


@override_settings(DESIGN_ASSEMBLIES_FOLDER=os.path.join(os.path.dirname(os.path.abspath(__file__)), 'testdata'))
class TranscriptTestCase(TestCase):

    def setUp(self) -> None:
        Organism.add_to_database('gencode test', 'chr1',
                                 os.path.join(os.path.dirname(os.path.abspath(__file__)), 'testdata', 'gencode.gff'),
                                 'source', 'gencode', 'sequencesearch', 'gencode test', silent=True)
        self.transcript = Transcript.objects.get(name='KLHL17-205')

    def test_extract_sequence(self):
        self.assertEqual(self.transcript.name, 'KLHL17-205')
        self.assertEqual(self.transcript.sequence, KLHL17_205_sequence)
        self.assertEqual(self.transcript.coding_sequence, KLHL17_205_cds)

    def test_cds_to_transcript_position(self):
        self.assertEqual(self.transcript.cds_to_transcript_position(0), 2068)

    def test_protein_to_transcript_position(self):
        self.assertEqual(self.transcript.protein_to_transcript_position(0), [2068, 2069, 2070])
        self.assertEqual(self.transcript.protein_to_transcript_position(69), [2275, 2276, 2277])
        self.assertEqual(self.transcript.protein_to_transcript_position(69, 1), [2275, 2276, 2277])
        self.assertEqual(self.transcript.protein_to_transcript_position(70), [2278, 2470, 2471])
        self.assertEqual(self.transcript.protein_to_transcript_position(70, 1), [2278, 2279, 2280])
        self.assertEqual(self.transcript.protein_to_transcript_position(71), [2472, 2473, 2474])
        self.assertEqual(self.transcript.protein_to_transcript_position(71, 1), [2281, 2473, 2474])

    def test_degenerate_sequence(self):
        self.assertEqual(self.transcript.degenerate_sequence,
                         [('ATGAARTGYGTNMGNYTNCCNYTNYTNWSNMGNGAYTTYYTNYTNGGNCAYGTNGAYGCNGARWSNYTNGTNMGNCAYCAYCCNGAYTGYAARGAYYTNYTNATHGARGCNYTNAARTTYCAYYTNYTNCCNGARCARMGNGGNGTNYTNGGNACNWSNMGNACNMGNCCNMGNMGNTGYGARGGNGCNGGNCCNGTNYTNTTYGCNGTNG', 2068),
                         ('GNGGNGGNWSNYTNTTYGCNATHCAYGGNGAYTGYGARGCNTAYGAYACNMGNACNGAYMGNTGGCAYGTNGTNGCNWSNATGWSNACNMGNMGNGCNMGNGTNGGNGTNGCNGCNGTNGGNAAYMGNYTNTAYGCNGTNGGNGG', 2470),
                         ('NTAYGAYGGNACNWSNGAYYTNGCNACNGTNGARWSNTAYGAYCCNGTNACNAAYACNTGGCARCCNGARGTNWSNATGGGNACNMGNMGNWSNTGYYTNGGNGTNGCNGCNYTNCAYGGNYTNYTNTAYWSNGCNGGNGGNTAYGAYGGNGCNWSNTGYYTNAAYWS', 2698),
                         ('NGCNGARMGNTAYGAYCCNYTNACNGGNACNTGGACNWSNGTNGCNGCNATGWSNACNMGNMGNMGNTAYGTNMGNGTNGCNACNYTNG', 3281),
                         ('AYGGNAAYYTNTAYGCNGTNGGNGGNTAYGAYWSNWSNWSNCAYYTNGCNACNGTNGARAA', 3468),
                         ('RTRR', 3710)])

